events {
    worker_connections  1024;
}

http {
    server {
        listen 80 default_server;
        server_name _;
        root /usr/share/nginx/html;
        location / {
            autoindex on;
            autoindex_format json;
        }
    }
}
